name: Node.js CI - Run Selenium Tests with Firefox

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Remove snap Firefox and install Firefox from PPA
        run: |
          sudo snap remove firefox || true
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install geckodriver
        run: |
          GECKO_VERSION="v0.33.0"
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKO_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Run tests
        run: npm test