name: Node.js CI - Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Firefox
        run: sudo apt-get update && sudo apt-get install -y firefox

      - name: Setup geckodriver
        uses: mozilla/geckodriver@v1
        with:
          version: latest

      - run: npm install

      - run: npm test